### ISSUE TITLE
Java 17 Support

### ISSUE THREAD

**Issue by svoitovich** [mariomac/kaconf#3]
I've been using `kaconf` and would really like to continue, but it doesn't seem to work with Java 17.

Here's the compile error:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.NoSuchFieldException: modifiers
        at info.macias.kaconf.Configurator.configure(Configurator.java:83)
        at info.macias.kaconf.Configurator.configure(Configurator.java:56)
        at com.apple.amp.aqe.epilog.App.launch(App.kt:16)
        at com.apple.amp.aqe.epilog.App$Companion.main(App.kt:23)
        at com.apple.amp.aqe.epilog.App.main(App.kt)
Caused by: java.lang.NoSuchFieldException: modifiers
        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
        at info.macias.kaconf.Configurator.configure(Configurator.java:79)
        ... 4 more

```

Is there a plan to fix it?

**Comment by mariomac** [comment]
@voytovichs version 0.9.1 has been published, fixing this crash.

However, if you use a java version higher than 11, you won't be able to assign values to `final` fields anymore. (Still working for java 11 or lower).
